title: CodingTed 
description: 能立能达,不怨不尤
url: http://www.codingted.com
author: Ted
email: teddzhaoo@gmail.com
img_server: /assets/img/blog
github: https://github.com/codingted
logo: assets/img/favicon.ico
keywords: 
  - Web
  - Linux
  - Bash
  - Vim

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"
markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!-- more -->"
highlighter: rouge
lsi: false
exclude: ['README.md', '.*', '_drafts', 'bin/', 'Gemfile', 'node_modules', '*.log', 'package.json']
kramdown:
  input: GFM
  hard_wrap: false

ga: 'UA-101505198-1'
disqus: 'www-codingted-com'
sass:
    style: compressed

collections:
  effective-cpp:
    output: true
    permalink: /:year/:month/:day/:title.html
  git-workflow:
    output: true
    permalink: /:year/:month/:day/:title.html
  vim-practice:
    output: true
    permalink: /:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: "_drafts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog"

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
